### ISSUE TITLE
Guzzle ~5

### ISSUE THREAD

**Issue by Daveawb** [LeaseWeb/chefauth-guzzle-plugin#2]
I've just updated this plugin on my local environment to use Guzzle 5.*'s event emmiter. 

I was wondering if you had written any tests for this package that you'd be willing to share. I've written some simple PHPSpec tests so far but nothing to heavy.

Thanks in advance

**Comment by nrocco** [comment]
Hi there. Unfortunatly the only tests I have for this plugin are part of a larger project's code base.
When I get around to it I will isolate them and commit them here.

Care to share your efforts with the guzzle 5.x event emitters?

**Comment by Daveawb** [comment]
No problem, happy to share. I'll send a pr this week.
